name: EMS Billing Specialists
favicon: null
layout_spectrum: 0.39639421342872083
typography_spectrum: 0.08050042996183038
title: EMS Billing Specialists
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#414141'
    - '#c7e5c3'
    - '#b8b8b8'
    - '#868686'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
