name: EMS Billing Specialists
favicon: null
layout_spectrum: 0.39639421342872083
typography_spectrum: 0.08050042996183038
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3457897203043103
  lightness: 0.42507199035026133
  saturation: 0.000623002415522933
  rhythmicContrast: 0.12159399013035
purpose: []
