name: EMS Billing Specialists
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: EMS Billing Specialists
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#414141'
    - '#c7e5c3'
    - '#b8b8b8'
    - '#868686'
  brandStrength: 0.3125
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
